---
- name: Copying war from master ansible to tomcat worker
  hosts: dev
  become: yes
  connection: ssh
  tasks:
  - name: Copying war
    copy:
      src: devops-mvn-webapp-2.war
      dest: /root/apache-tomcat-9.0.97/webapps/